### ISSUE TITLE
Maven install issue

### ISSUE THREAD

**Issue by ycrouin** [shraga89/Ontobuilder-Research-Environment#10]
Hi, thanks for open-sourcing this tool :)

I'm currently working on schema matching for an internship and I wish to give this tool a try.

Unfortunately, I'm not able to install/test the Maven project. I tried to do it for both the master and add_pom branches but wasn't successful. I'm not familiar with Java so I'm not sure how to solve the issue.

**master branch** When I try to install for the master branch, I get the following error quite early on:
```
[ERROR] Failed to execute goal on project ore: Could not resolve dependencies for project ac.technion.schemamatching:ore:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: de.wdilab:coma-engine:jar:0.1-CE-SNAPSHOT, org.deckfour:log:jar:0.1-CE-SNAPSHOT, org.deckfour:xes:jar:0.1-CE-SNAPSHOT: Could not find artifact de.wdilab:coma-engine:jar:0.1-CE-SNAPSHOT at specified path /home/ycrouin/Desktop/ORE/Ontobuilder-Research-Environment-master/lib/coma/engine.jar
```
I also saw that maven wasn't able to download the packages from git: `unable to fetch maven-metadata for package : "maven package "com.google.guava.guava" does not exist under owner "shraga89""` for the following download URL : `https://maven.pkg.github.com/tomersagi/ontobuilderDev/com/google/guava/guava/maven-metadata.xml`.

**add_pom branch** Then I saw a ticket talking about the `add_pom` branch so I decided to test the install again on this branch.
The build is going further and some packages are successfully downloaded from `github` and `github_out`, however, I meet an other similar error later on in the build:
```
[ERROR] Failed to execute goal on project ore: Could not resolve dependencies for project ac.technion.schemamatching:ore:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: de.wdilab:coma-engine:jar:0.1-CE-SNAPSHOT, org.deckfour:log:jar:0.1-CE-SNAPSHOT, org.deckfour:xes:jar:0.1-CE-SNAPSHOT: Could not find artifact de.wdilab:coma-engine:jar:0.1-CE-SNAPSHOT at specified path /home/ycrouin/Desktop/ORE/Ontobuilder-Research-Environment-master/lib/coma/engine.jar
```

Here is the output of `mvn --version` in case it helps:
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-53-generic", arch: "amd64", family: "unix"
```

For completeness, I attach the log of `mvn test -U -B` for each branch below:
[mvn-test-master.txt](https://github.com/shraga89/Ontobuilder-Research-Environment/files/6538629/mvn-test-master.txt)
[mvn-test-add_pom.txt](https://github.com/shraga89/Ontobuilder-Research-Environment/files/6538631/mvn-test-add_pom.txt)

**Comment by tomersagi** [comment]
ok, I will have a look at it.

**Comment by tomersagi** [comment]
First of all, if you use the master branch, you need to do an ANT build and not maven. 
If you use the add_pom branch you can do a maven install. 
Did you try our installation instructions here:

https://github.com/shraga89/Ontobuilder-Research-Environment/blob/master/wiki/Installation.md

**Comment by ycrouin** [comment]
Hi, thanks for getting back to me so fast.
Yes, I did try the installation instructions there.

A few differences though: I installed MySQL 8 instead of MySQL 5.7, and I didn't install any java IDE (neither Eclipse nor Intellij), however, I don't think this could be the source of these errors right?

**Comment by tomersagi** [comment]
Try 'mvn clean' and post the full log.

**Comment by ycrouin** [comment]
Hi, I have good news!
After running `mvn clean`, I ran `mvn test` again and now it works fine :)
I'm not sure why but I guess there was some kind of conflict in the process at some point.
You can close the issue, thank you very much for your help!

**Comment by tomersagi** [comment]
Yeah for some reasonyyou need to run clean before anything else, although
clean is supposed to be included in anything else. Go figure maven 🤷‍♂️

**Comment by Issac-Newton** [comment]
I also meet the same problem, the error said couldn't find the  **coma.engine.jar**  under lib/
I search in the lib, it doesn't exist.

**Comment by tomersagi** [comment]
Different cause - you probably were not on the same branch. Coma support was removed from the add_pom branch. Use that branch for any maven-related build. The master branch does not support maven builds you need to use ANT to build in the master branch.

**Comment by Issac-Newton** [comment]
Thanks for your replay, I tried your answer, but it doesn't work on the **add_pom** branch, the error Information is 

`Failed to execute goal on project ore: Could not resolve dependencies for project ac.technion.schemamatching:ore:jar:1.1-SNAPSHOT: Could not transfer artifact javax.wsdl:wsdl4j:jar:1.5.1 from/to Talan (https://nexus.talanlabs.com/content/repositories/releases/): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]`

The web site above need login, I searched in the javax.wsdl4j.pom and put it into .m2/repository, but is still try to download the jar from **nexus.talanlabs** , I haven't find the setting for javax.wsdl4j.jar, if so, please teach me, thanks.

Besides, I have a question on the master branch, I didn't find the **build.xml** for **ant**. I wonder if I have some misunderstanding for ant.

**Comment by tomersagi** [comment]
That's a new one. I will have a look. Maybe talan is offline.

**Comment by tomersagi** [comment]
@Issac-Newton Fixed this by replacing the offending jar with a new version from maven central on Ontobuilder-IO [here](https://github.com/shraga89/ontobuilderDev/commit/0774408abd18e0cf1b3d252e41f2531ef2bdf024)

**Comment by JZCS2018** [comment]
Hi I recently use this package for experiment. I downloaded the add_pom branch, and when I typed the mvn test, it will give me error, even though I tried mvn clean. Here is the error message, 
`[ERROR] Failed to execute goal on project ore: Could not resolve dependencies for project ac.technion.schemamatching:ore:jar:1.1-SNAPSHOT: Failed to collect dependencies at ac.technion.schemamatching:ontobuilder.core:jar:2.0-SNAPSHOT: Failed to read artifact descriptor for ac.technion.schemamatching:ontobuilder.core:jar:2.0-SNAPSHOT: Could not transfer artifact ac.technion.schemamatching:ontobuilder.core:pom:2.0-SNAPSHOT from/to github (https://maven.pkg.github.com/shraga89/ontobuilderDev): authentication failed for https://maven.pkg.github.com/shraga89/ontobuilderDev/ac/technion/schemamatching/ontobuilder.core/2.0-SNAPSHOT/ontobuilder.core-2.0-SNAPSHOT.pom, status: 401 Unauthorized -> [Help 1]`

Could you help me with this? I know you are busy, and I really appreciate your kind help!

**Comment by tomersagi** [comment]
Did you follow the installation instructions? You need to set up your
settings.xml file such that it has an access token to github.

**Comment by JZCS2018** [comment]
Thanks for your response, I figured I got a typo for the token...

When I run the experiments(OBExperimentRunner.java), the compiler always threw an error that `/Users/main/Desktop/Ontobuilder-Research-Environment/src/main/java/ac/technion/schemamatching/matching/OREMatchHandler.java:3:49
java: cannot access ac.technion.iem.ontobuilder.core.ontology.Ontology
  bad class file: /Users/main/.m2/repository/ac/technion/schemamatching/ontobuilder.core/2.0-SNAPSHOT/ontobuilder.core-2.0-20220218.163851-4.jar!/ac/technion/iem/ontobuilder/core/ontology/Ontology.class
    class file has wrong version 55.0, should be 52.0`

when I tried the server, there is no such file as ore.jar. Got confused about it. Thanks for helping me!

**Comment by JZCS2018** [comment]
Thanks, I got that!
